apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: mawlana/user
          ports:
            - containerPort: 3002
          env:
            - name: USER_PORT
              value: '3002'
            - name: DATABASE_URL
              value: 'mongodb+srv://dangeroust:1468957542@childcare.fig6g8g.mongodb.net/%25retryWrites=true&w=majority'
            - name: RMQ_URI
              value: 'amqps://txgsohca:VETHVuZQ4Ffc5igGLvPhsuucvkpdWGnp@rattlesnake.rmq.cloudamqp.com/txgsohca'
            - name: ACCESS_SECRET
              value: Mwalana
            - name: AT_SECRET
              value: Mawlana
            - name: CLOUD_NAME
              value: dxg8aacuw
            - name: CLOUD_API_KEY
              value: '684589892879949'
            - name: CLOUD_API_SECRET
              value: QEYWjB_UEHvcKHDCUBef42gsX-g
